%% 01_基础控件.m — uifigure 基础控件
%  涵盖: uifigure, uibutton, uitextfield, uislider, uidropdown
%  基础 MATLAB 即可

clear; clc; close all;

%% ===== 1. 创建基本窗口 =====
fprintf('===== 1. 创建基本窗口 =====\n');

% 创建 App 窗口
fig = uifigure('Name', 'MATLAB GUI 基础控件', ...
    'Position', [100 100 600 500]);

% 添加面板
pnl = uipanel(fig, 'Title', '基础控件演示', ...
    'Position', [20 20 560 460]);

fprintf('窗口创建成功: %s\n', fig.Name);

%% ===== 2. 标签与按钮 =====
fprintf('\n===== 2. 标签与按钮 =====\n');

% 文本标签
lbl = uilabel(pnl, 'Text', '欢迎使用 MATLAB GUI!', ...
    'FontWeight', 'bold', 'FontSize', 14, ...
    'FontColor', [0.2 0.2 0.8], ...
    'Position', [20 400 300 30]);

% 普通按钮
btn_click = uibutton(pnl, 'Text', '点击我', ...
    'Position', [20 350 100 35], ...
    'BackgroundColor', [0.3 0.6 0.9], ...
    'FontColor', 'white', ...
    'ButtonPushedFcn', @(src,evt) disp('按钮被点击了!'));

% 状态按钮
btn_toggle = uitogglebutton(pnl, 'Text', '开关按钮', ...
    'Position', [140 350 100 35], ...
    'ValueChangedFcn', @(src,evt) fprintf('开关状态: %s\n', ...
        matlab.lang.Boolean(true, src.Value)));

%% ===== 3. 文本输入 =====
fprintf('\n===== 3. 文本输入 =====\n');

% 单行文本框
uilabel(pnl, 'Text', '请输入姓名:', ...
    'Position', [20 300 80 20]);

edit_name = uieditfield(pnl, 'text', ...
    'Position', [110 298 150 25], ...
    'Placeholder', '在此输入...');

% 数值输入框
uilabel(pnl, 'Text', '请输入年龄:', ...
    'Position', [20 265 80 20]);

edit_age = uieditfield(pnl, 'numeric', ...
    'Position', [110 263 150 25], ...
    'Limits', [0 150], ...
    'Value', 25);

% 文本区域 (多行)
uilabel(pnl, 'Text', '备注:', ...
    'Position', [20 230 80 20]);

ta = uitextarea(pnl, ...
    'Position', [110 160 200 90], ...
    'Placeholder', '多行文本输入...');

%% ===== 4. 滑块与下拉框 =====
fprintf('\n===== 4. 滑块与下拉框 =====\n');

% 滑块
uilabel(pnl, 'Text', '调节亮度:', ...
    'Position', [20 130 80 20]);

lbl_slider_val = uilabel(pnl, 'Text', '50', ...
    'Position', [430 130 40 20], ...
    'HorizontalAlignment', 'center');

sld = uislider(pnl, ...
    'Position', [110 130 310 15], ...
    'Limits', [0 100], ...
    'Value', 50, ...
    'ValueChangedFcn', @(src,evt) set(lbl_slider_val, 'Text', ...
        sprintf('%.0f', src.Value)));

% 下拉框
uilabel(pnl, 'Text', '选择颜色:', ...
    'Position', [20 90 80 20]);

dd_color = uidropdown(pnl, ...
    'Position', [110 88 150 25], ...
    'Items', {'红色', '绿色', '蓝色', '黄色'}, ...
    'ValueChangedFcn', @(src,evt) fprintf('选择了: %s\n', src.Value));

% 复选框
chk = uicheckbox(pnl, ...
    'Text', '启用高级模式', ...
    'Position', [20 55 150 25], ...
    'ValueChangedFcn', @(src,evt) fprintf('高级模式: %s\n', ...
        ternary(src.Value, '开启', '关闭')));

%% ===== 5. 列表与单选按钮 =====
fprintf('\n===== 5. 列表与单选按钮 =====\n');

% 单选按钮组
rbg = uibuttongroup(pnl, 'Title', '数据格式', ...
    'Position', [300 50 220 100]);

rb1 = uiradiobutton(rbg, 'Text', 'CSV', ...
    'Position', [10 65 80 25]);
rb2 = uiradiobutton(rbg, 'Text', 'Excel', ...
    'Position', [10 40 80 25]);
rb3 = uiradiobutton(rbg, 'Text', 'JSON', ...
    'Position', [10 15 80 25]);
rbg.SelectedButton = rb1;

% 列表框
uilabel(pnl, 'Text', '变量列表:', ...
    'Position', [300 170 80 20]);

lb = uilistbox(pnl, ...
    'Position', [300 220 200 120], ...
    'Items', {'x (double)', 'y (cell)', 'data (table)', 'img (uint8)'}, ...
    'Multiselect', 'on');

%% ===== 6. 信息汇总 =====
fprintf('\n===== 6. 控件属性汇总 =====\n');

% 提交按钮
btn_submit = uibutton(pnl, 'Text', '提交', ...
    'Position', [300 20 100 35], ...
    'BackgroundColor', [0.2 0.7 0.3], ...
    'FontColor', 'white', ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(src,evt) callback_submit());

function callback_submit()
    fprintf('\n===== 提交信息 =====\n');
    fprintf('姓名: %s\n', edit_name.Value);
    fprintf('年龄: %d\n', edit_age.Value);
    fprintf('备注: %s\n', ta.Value);
    fprintf('亮度: %.0f\n', sld.Value);
    fprintf('颜色: %s\n', dd_color.Value);
    fprintf('格式: %s\n', rbg.SelectedButton.Text);
    fprintf('选中变量: ');
    for i = 1:length(lb.Value)
        fprintf('%s ', lb.Value{i});
    end
    fprintf('\n');
end

% 辅助函数
function result = ternary(cond, true_val, false_val)
    if cond; result = true_val; else; result = false_val; end
end

fprintf('GUI 窗口已创建，请操作各控件查看效果\n');
fprintf('\n===== 基础控件模块完成! =====\n');
